development: &default
  adapter: postgresql
  encoding: unicode
  database: crossword-genius_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: crossword-genius_test
